- name: create dir for checks
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items:
    - /opt/datadog/conf.d/
  become: yes

- name: setup checks
  template:
    src: "{{ item }}.yaml"
    dest: /opt/datadog/conf.d/{{ item }}.yaml
  with_items:
    - docker_daemon
