- name: get the datadog docker image
  docker_image:
    name: datadog/docker-dd-agent
  become: yes

- name: run the datadog container
  docker_container:
    name: datadog
    image: datadog/docker-dd-agent:latest
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    env:
      API_KEY: "{{ datadog.api_key }}"
      SD_BACKEND: docker
      NON_LOCAL_TRAFFIC: false
    restart_policy: always 
  become: yes
