- name: make sure dirs exist
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  with_items:
    - /mnt/deluge/config
    - /mnt/deluge/downloads

- name: load vars from disk
  include_vars: "{{ deluge.vars_file }}"

- name: set up core configs
  template:
    src: core.conf.j2
    dest: /mnt/deluge/config/core.conf

- name: configure notifications
  template:
    src: "{{ item }}.j2"
    dest: /mnt/deluge/config/{{ item }}
    mode: 0755
  with_items:
    - execute_completed.sh
    - execute_added.sh

- name: setup execute plugin configs
  template:
    src: execute.conf.j2
    dest: /mnt/deluge/config/execute.conf
