- name: make sure dirs exist
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  with_items:
    - /mnt/deluge/config
    - /mnt/deluge/downloads

- name: load vars from disk
  include_vars: "{{ deluge.vars_file }}"

- name: set up configs
  template:
    src: core.conf.j2
    dest: /mnt/deluge/config/core.conf


