- name: create pia_network
  docker_network:
    name: pia_network
  become: yes

#- name: make dirs
#  file:
#    state: directory
#    path: "{{ item }}"
#  with_items:
#    - /mnt/pia/
#
#- name: create auth.conf
#  template:
#    src: auth.conf.j2
#    dest: /mnt/pia/auth.conf

- name: get the docker image
  docker_image:
    name: colinhebert/pia-openvpn
  become: yes

- name: load creds
  include_vars: "{{ pia.vars_file }}"

- name: run the container
  docker_container:
    name: pia
    image: colinhebert/pia-openvpn:latest
    capabilities:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns_servers:
      - 209.222.18.218
      - 209.222.18.222
    env:
      REGION: "US Texas"
      USERNAME: "{{ pia.username }}"
      PASSWORD: "{{ pia.password }}"
 #   volumes:
 #     - /mnt/pia/auth.conf:/auth.conf
    networks:
      - name: pia_network
    #command: colinhebert/pia-openvpn --pull --auth-user-pass /auth.conf
    restart_policy: always
  become: yes
