- name: make sure dirs exist
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  with_items:
    - /mnt/sonarr/config
  become: yes
