- name: make sure dirs exist
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  with_items:
    - /mnt/sonarr/config
  become: yes

- name: get the sonarr docker image
  docker_image:
    name: linuxserver/sonarr
  become: yes

- name: run the sonarr container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr:latest
    network_mode: host
    volumes:
      #- /etc/localtime:/etc/localtime:ro # either this or TZ env var is required
      - /mnt/sonarr:/config
      - /mnt/plex/media/tv:/tv
      - /mnt/deluge/downloads:/downloads
    env:
      TZ: "America/Chicago"
      PUID: "{{ ansible_user_uid }}"
      GUID: "{{ ansible_user_gid }}"
    ports:
      - 8989:8989
    restart_policy: always
  become: yes
