- name: make sure dirs exist
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  with_items:
    - /mnt/plex/config
    - /mnt/plex/transcode
    - /mnt/plex/media/movies
    - /mnt/plex/media/music
    - /mnt/plex/media/tv
  become: yes
