- name: make sure dirs exist
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    state: directory
  with_items:
    - /mnt/plex/config
    - /mnt/plex/transcode
    - /mnt/plex/media/movies
    - /mnt/plex/media/music
    - /mnt/plex/media/tv
  become: yes

- name: get the plex docker image
  docker_image:
    name: plexinc/pms-docker
  become: yes

- name: run the plex container
  docker_container:
    name: plex
    image: plexinc/pms-docker:latest
    network_mode: host
    volumes:
      - /mnt/plex/config:/config
      - /mnt/plex/transcode:/transcode
      - /mnt/plex/media:/data
    env:
      TZ: "America/Chicago"
      PLEX_CLAIM: "CLAIM-DHH3JAHCM2TFBZPDRWTN"
      HOSTNAME: "hal"
      PLEX_UID: "{{ ansible_user_uid }}"
      PLEX_GID: "{{ ansible_user_gid }}"
    restart_policy: always
  become: yes
